# FAKE NEWS DETECTION

This project Involves building a model that will predict with text(news statement) if a news is FAKE or REAL.

This is a SUPERVISED learning with a CLASSIFICATION (BINARY) problem

#### PROJECT FLOW

        DATA COLLECTION
              ↓
        DATA UNDERSTANDING
              ↓
        DATA CLEANING  
              ↓
        EDA / DATA ANALYSIS
              ↓
        TEXT PREPROCESSING
              ↓
        TRAIN / TEST SPLIT
              ↓
        TEXT VECTORIZATION / ENCODING
              ↓
        MODEL TRAINING & VALIDATION
              ↓
        MODEL EVALUATION
              ↓
        MODEL TUNING
              ↓
        FINAL MODEL
              ↓
        DEPLOYMENT

                    TF-IDF
                       ↓
              ┌────────┼────────┐
              ↓        ↓        ↓
        Logistic     Linear    Naive
        Regression     SVM      Bayes
              ↓        ↓        ↓
              └────────┼────────┘
                       ↓
                  Compare metrics
                       ↓
                 Select final model

In [1]:
import pandas as pd

In [2]:
# Import the data

data=pd.read_excel(r"C:\Users\USER\Downloads\Kaggle DataSet\fake_or_real_news.csv.xlsx")
data.head(5)

,id,title,text,label,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 131,Unnamed: 132,Unnamed: 133,Unnamed: 134,Unnamed: 135,Unnamed: 136,Unnamed: 137,Unnamed: 138,Unnamed: 139,Unnamed: 140
0,8476,You Can Smell Hillaryâ€™s Fear,"Daniel Greenfield, a Shillman Journalism Fello...",FAKE,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,10294,Watch The Exact Moment Paul Ryan Committed Pol...,Google Pinterest Digg Linkedin Reddit Stumbleu...,FAKE,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3608,Kerry to go to Paris in gesture of sympathy,U.S. Secretary of State John F. Kerry said Mon...,REAL,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,10142,Bernie supporters on Twitter erupt in anger ag...,"â€” Kaydee King (@KaydeeKing) November 9, 2016...",FAKE,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,875,The Battle of New York: Why This Primary Matters,It's primary day in New York and front-runners...,REAL,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7795 entries, 0 to 7794
Columns: 141 entries, id to Unnamed: 140
dtypes: object(141)
memory usage: 8.4+ MB

In [4]:
data.isna().sum()

id               247
title            610
text             866
label           1040
Unnamed: 4      7477
                ...
Unnamed: 136    7794
Unnamed: 137    7794
Unnamed: 138    7794
Unnamed: 139    7794
Unnamed: 140    7794
Length: 141, dtype: int64

In [5]:
data.columns

Index(['id', 'title', 'text', 'label', 'Unnamed: 4', 'Unnamed: 5',
       'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       ...
       'Unnamed: 131', 'Unnamed: 132', 'Unnamed: 133', 'Unnamed: 134',
       'Unnamed: 135', 'Unnamed: 136', 'Unnamed: 137', 'Unnamed: 138',
       'Unnamed: 139', 'Unnamed: 140'],
      dtype='object', length=141)

### Data Cleaning

In [6]:
# Remove rredundant columns 
df= data[['id', 'title', 'text', 'label']]
df.head()

,id,title,text,label
0,8476,You Can Smell Hillaryâ€™s Fear,"Daniel Greenfield, a Shillman Journalism Fello...",FAKE
1,10294,Watch The Exact Moment Paul Ryan Committed Pol...,Google Pinterest Digg Linkedin Reddit Stumbleu...,FAKE
2,3608,Kerry to go to Paris in gesture of sympathy,U.S. Secretary of State John F. Kerry said Mon...,REAL
3,10142,Bernie supporters on Twitter erupt in anger ag...,"â€” Kaydee King (@KaydeeKing) November 9, 2016...",FAKE
4,875,The Battle of New York: Why This Primary Matters,It's primary day in New York and front-runners...,REAL

In [7]:
# Check for duplicates
df.duplicated().sum()

np.int64(228)

This can means that 228 rows are exact duplicates of an earlier row across all columns.

The next step is to investigate which rows they are and what is being duplicated.
So let's investigate further

In [8]:
# Display the duplicated rows
duplicates = df[df.duplicated(keep=False)]

duplicates

       id title text label
258   NaN   NaN  NaN   NaN
260   NaN   NaN  NaN   NaN
262   NaN   NaN  NaN   NaN
264   NaN   NaN  NaN   NaN
266   NaN   NaN  NaN   NaN
...   ...   ...  ...   ...
7248  NaN   NaN  NaN   NaN
7250  NaN   NaN  NaN   NaN
7252  NaN   NaN  NaN   NaN
7254  NaN   NaN  NaN   NaN
7256  NaN   NaN  NaN   NaN

[233 rows x 4 columns]

That means these aren't necessarily 233 duplicated news articles. They are likely completely empty rows that appear multiple times.
Pandas consider empty space as duplicated cells

In [9]:
# Count completely empty rows

empty_rows = df[df.isna().all(axis=1)]

print("Completely empty rows:", len(empty_rows))

Completely empty rows: 221

In [10]:
# Check for exact duplicates of non-empty rows
df_clean = df.dropna(how='all')

df_clean.duplicated().sum()

np.int64(8)

Let's check missing data and handle it first, then wiull come back to reconfirm the number duplicate we have, if any.

In [11]:
# Examine for missing data
df.isna().sum().sum()

np.int64(2763)

In [12]:
print(df.isna().sum())
print(f"Total rows with missing values: {df.isna().any(axis=1).sum()}")

id        247
title     610
text      866
label    1040
dtype: int64
Total rows with missing values: 1061

we have 2763 missing values but only 1061 affected rows;
This means the missing values are overlapping in the same records (they are concentrated in the same rows)
We have 13% of the data missing. Best practice is to drop them and keep roughly 7,000 clean rows.

In [13]:
# Drop the missing values

# Create a df copy
df_clean = df.copy()

In [14]:
# Remove only completely empty data
df_clean = df_clean.dropna(how='all')

In [15]:
# Examine the cleaned data

print("Rows remaining:", len(df_clean))
print("Completely empty rows:", df_clean.isna().all(axis=1).sum())

Rows remaining: 7574
Completely empty rows: 0

In [16]:
df_clean.isna().sum().sum()

np.int64(1879)

In [17]:
# Remove rows with missing rows

df_clean = df_clean.dropna(subset=['label'])

print("Rows remaining:", len(df_clean))
print("Missing labels:", df_clean['label'].isna().sum())

Rows remaining: 6755
Missing labels: 0

In [18]:
df_clean.isna().sum().sum()

np.int64(21)

In [19]:
print("Missing text:", df_clean['text'].isna().sum())
print("Usable text:", df_clean['text'].notna().sum())

Missing text: 1
Usable text: 6754

In [20]:
# Examine the number missing brows in text and title columns
print("Both title and text missing:",
      (df_clean['title'].isna() & df_clean['text'].isna()).sum())

print("Title missing, text available:",
      (df_clean['title'].isna() & df_clean['text'].notna()).sum())

print("Text missing, title available:",
      (df_clean['text'].isna() & df_clean['title'].notna()).sum())

Both title and text missing: 0
Title missing, text available: 0
Text missing, title available: 1

In [21]:
# Remove the missing row in text column
df_clean = df_clean.dropna(subset=['text'])

print("Rows remaining:", len(df_clean))
print("Missing text:", df_clean['text'].isna().sum())

Rows remaining: 6754
Missing text: 0

In [22]:
df_clean.isna().sum().sum()

np.int64(20)

This missing rows is coming from ID column and its not needed in the data modelling

The step-by-step approach lets us make a decision based on the role of each column

In [23]:
# Check label values

#print(df_clean['label'].value_counts(dropna=False))
#print("\nUnique labels:")
#print(df_clean['label'].unique())

In [24]:
# instigate the labels with the actual data and others 
print("FAKE:", (df_clean['label'] == 'FAKE').sum())
print("REAL:", (df_clean['label'] == 'REAL').sum())

print("Other labels:",
      (~df_clean['label'].isin(['FAKE', 'REAL'])).sum())

FAKE: 3154
REAL: 3161
Other labels: 439

In [25]:
# Create a new df of labels that are not the correct labels and displays the first 20 rows of those problematic records.

bad_labels = df_clean[
    ~df_clean['label'].isin(['FAKE', 'REAL'])
]

print(bad_labels[['id', 'title', 'text', 'label']].head(5).to_string())

                                                                                     id                                                                                                                                                     title                                                                                                                                                                            text                                                                                                                                                                                                                label
257                       g campaign â€¦ the epic dark saga will unfold this way: A man                                                                                                                           filled with fear and insecurity                                                                                                   created a hatemongering character and followed it out the window. And a woman                                                                                                                                                                                      filled with fear and insecurity
259                                                                                 NaN                                                                                                   part twoâ€: â€œBill Clintonâ€™s Presidency was defined                                                                                                                                                               for the most part                                                                                                                                                                         by criminal and congressional investigations
261                                                                                 NaN  â€ says the New York Timesâ€™ Editorial Board. â€œFor many voters that will mean defying Republican efforts to jam the electoral machinery through lies                                                                                                      legal obstructions and the threat of violence. We hope the voters hold out                                                                                        however intimidating the process and long the lines. For Americans who may feel unmoved or unwilling to vote for Mrs. Clinton
263  -- ""The Wall Street Journal hasnâ€™t endorsed a presidential candidate since 1928                                           and if we didnâ€™t endorse Ronald Reagan we arenâ€™t about to revive the practice for Mrs. Clinton or Mr. Trump                                                                 Â the Journalâ€™s board declares. â€œA broken Washington needs to be shaken up and refocused on the public good   and who better to do it than an outsider beholden to neither political party? If only that reform possibility didnâ€™t arrive as a flawed personality who has few convictions and knows little about the world.â€
267                                                                                 NaN                                                                               U.S. backed force in Syria launched an offensive to retake control of Raqqa   seeking to drive out Islamic State militants from their northeastern stronghold. The operation with the U.S.-supported military effort to seize the Mosul from ISIS militants                    Hugh Naylor writes. And the impending assault represents an â€œintensified international effortâ€ to increase pressure on the extremist group as it loses control of territory in the countries.

In [26]:
valid_labels = ['FAKE', 'REAL']

print("Total rows:", len(df_clean))

print("Valid labels:",
      df_clean['label'].isin(valid_labels).sum())

print("Invalid labels:",
      (~df_clean['label'].isin(valid_labels)).sum())

Total rows: 6754
Valid labels: 6315
Invalid labels: 439

So this 439 other rows are the corrupted records we identified.

In [27]:
print(df_clean[df_clean['label'].isin(['FAKE', 'REAL'])]['label'].value_counts())

label
REAL    3161
FAKE    3154
Name: count, dtype: int64

In [28]:
# Remove the corrupted labels

valid_labels = ['FAKE', 'REAL']

df_clean = df_clean[
    df_clean['label'].isin(valid_labels)
].copy()

In [29]:
# Verify the label column now

print("Rows remaining:", len(df_clean))
print("\nLabel distribution:")
print(df_clean['label'].value_counts())

print("\nMissing values:")
print(df_clean.isna().sum())

Rows remaining: 6315

Label distribution:
label
REAL    3161
FAKE    3154
Name: count, dtype: int64

Missing values:
id       0
title    0
text     0
label    0
dtype: int64

In [30]:
# Examine the column and values datatypes

print(df_clean.dtypes)

print("\nText column types:")
print(df_clean['text'].map(type).value_counts())

print("\nTitle column types:")
print(df_clean['title'].map(type).value_counts())

print("\nLabel column types:")
print(df_clean['label'].map(type).value_counts())

id       object
title    object
text     object
label    object
dtype: object

Text column types:
text
<class 'str'>                  6314
<class 'datetime.datetime'>       1
Name: count, dtype: int64

Title column types:
title
<class 'str'>    6315
Name: count, dtype: int64

Label column types:
label
<class 'str'>    6315
Name: count, dtype: int64

In [31]:
# I dentify the rwo with the datatime type

non_string_text = df_clean[
    ~df_clean['text'].map(lambda x: isinstance(x, str))
]

print(non_string_text[['id', 'title', 'text', 'label']].to_string())

        id                                  title                 text label
3156  8751  2009 FLASHBACK: â€œWhat Ifâ€ Remixed  2016-08-11 00:00:00  FAKE

In [32]:
# delete the row where datetime is text

df_clean = df_clean[
    df_clean['text'].map(lambda x: isinstance(x, str))
].copy()

This output just revealed something critical in the data: 3156  8751  2009 FLASHBACK: â€œWhat Ifâ€ Remixed  2016-08-11 00:00:00  FAKE.
This means that some values in the text and title columns has character encoding issues which needs to be solved else then model might not learn corrected but with noises that exist in the data\

In [33]:
df_clean.head()

,id,title,text,label
0,8476,You Can Smell Hillaryâ€™s Fear,"Daniel Greenfield, a Shillman Journalism Fello...",FAKE
1,10294,Watch The Exact Moment Paul Ryan Committed Pol...,Google Pinterest Digg Linkedin Reddit Stumbleu...,FAKE
2,3608,Kerry to go to Paris in gesture of sympathy,U.S. Secretary of State John F. Kerry said Mon...,REAL
3,10142,Bernie supporters on Twitter erupt in anger ag...,"â€” Kaydee King (@KaydeeKing) November 9, 2016...",FAKE
4,875,The Battle of New York: Why This Primary Matters,It's primary day in New York and front-runners...,REAL

In [34]:
# lets install ftfy, a library specifically designed to fix Unicode/encoding problems:

!pip install ftfy

Requirement already satisfied: ftfy in c:\users\user\anaconda3\lib\site-packages (6.3.1)
Requirement already satisfied: wcwidth in c:\users\user\anaconda3\lib\site-packages (from ftfy) (0.2.13)

In [35]:
# Import 'fix_text' and apply it in the 'text' and 'title' columns
from ftfy import fix_text

df_clean['title'] = df_clean['title'].apply(fix_text)
df_clean['text'] = df_clean['text'].apply(fix_text)

In [36]:
df_clean.head()

,id,title,text,label
0,8476,You Can Smell Hillary's Fear,"Daniel Greenfield, a Shillman Journalism Fello...",FAKE
1,10294,Watch The Exact Moment Paul Ryan Committed Pol...,Google Pinterest Digg Linkedin Reddit Stumbleu...,FAKE
2,3608,Kerry to go to Paris in gesture of sympathy,U.S. Secretary of State John F. Kerry said Mon...,REAL
3,10142,Bernie supporters on Twitter erupt in anger ag...,"— Kaydee King (@KaydeeKing) November 9, 2016 T...",FAKE
4,875,The Battle of New York: Why This Primary Matters,It's primary day in New York and front-runners...,REAL

In [37]:
patterns = ['â€œ', 'â€', 'â€™', 'â€“', 'â€”']

for pattern in patterns:
    count_title = df_clean['title'].str.contains(pattern, na=False).sum()
    count_text = df_clean['text'].str.contains(pattern, na=False).sum()

    print(f"{pattern} -> titles: {count_title}, texts: {count_text}")

â€œ -> titles: 0, texts: 0
â€ -> titles: 0, texts: 3
â€™ -> titles: 0, texts: 0
â€“ -> titles: 0, texts: 0
â€” -> titles: 0, texts: 0

Fix the 3 text values that still contain corrupted sequence.

In [38]:
df_clean['text'] = df_clean['text'].str.replace(
    'â€', '"', regex=False
)

In [39]:
df_clean['text'] = df_clean['text'].str.replace(
    'â€Ś', '…', regex=False
)

In [40]:
# Confirm
patterns = ['â€œ', 'â€', 'â€™', 'â€“', 'â€”', 'â€Ś']

for pattern in patterns:
    count_title = df_clean['title'].str.contains(pattern, na=False).sum()
    count_text = df_clean['text'].str.contains(pattern, na=False).sum()

    print(f"{pattern} -> titles: {count_title}, texts: {count_text}")

â€œ -> titles: 0, texts: 0
â€ -> titles: 0, texts: 0
â€™ -> titles: 0, texts: 0
â€“ -> titles: 0, texts: 0
â€” -> titles: 0, texts: 0
â€Ś -> titles: 0, texts: 0

In [41]:
# Check for duplicates

print("Exact duplicate rows:", df_clean.duplicated().sum())

print("Duplicate texts:", df_clean['text'].duplicated().sum())

duplicate_texts = df_clean[
    df_clean['text'].duplicated(keep=False)
].sort_values('text')

print(duplicate_texts[['id', 'title', 'label']].head(30).to_string(index=False))

Exact duplicate rows: 0
Duplicate texts: 275
   id                                                                                                       title label
10386                          Israeli Minister sparks Scandal after showing Satisfaction for Italy's Earthquakes  FAKE
10008                           Israeli Minister sparks Scandal after showing Satisfaction at Italy's Earthquakes  FAKE
 8548                                                     A Mormon Reader Says Most Mormons Will Still Back Trump  FAKE
 8626                                                                                                World War 3?  FAKE
 8332                                        MARKETWATCH LEFTIST: MSM's "Blatant" Anti Trump Bias May Be Suicidal  FAKE
 9314                            Southern Poverty Law Center Targets Anti-Jihad Crusaders (Ann Corcoran Honored!)  FAKE
 8601                                   Pro-sovereignty Legislators Demand That Administration End Border Anarchy  FAKE
 6311                                   Radio Derb transcript for October 29th is up: The arrogance of power, Etc  FAKE
10304                                                    Refugee Resettlement Watch: Swept Away In North Carolina  FAKE
 6714         Is your promising internet career over now Vine is dead? Write for NewsBiscuit to cheer yourself up  FAKE
 9474        Michael Bloomberg Names Technological Unemployment as the Next Administration's "Greatest Conundrum"  FAKE
 9070              Round Up the Unusual Suspects: Moneyball Nerds Squeeze Out Blacks & Latinos from Baseball Jobs  FAKE
 7048                                                        Comment software has been rolled back to old version  FAKE
 9337                                   Radio Derb Is On The Air–Leonardo And Brazil's Miss Bum Bum Pageant, Etc.  FAKE
 5427              Thomas Frank Explores Whether Hillary Clinton and the Democratic Party Will Address Inequality  FAKE
 5367                                  NATIONAL REVIEW, Conservatism Inc., Plan To Cave EVEN MORE On Immigration!  FAKE
 6733                 The Comey Confrontation: In Our New Third-World America, Corruption Is A Feature, Not A Bug  FAKE
 5802                      Alert News : Putins Army Is Coming For World War3 Against Obama year 2016 New Video!!!  FAKE
 5715                                                                   Hope for the best, prepare for the worst…  FAKE
10193                                                   "Donald Trump And The Rise Of White Identity In Politics"  FAKE
 9564    An LDS Reader Takes A Look At Trump Accuser Jessica Drake, Concludes His Leaders Are "Latter-Day Sissies  FAKE
 5752                              America's Senator Jeff Sessions Warns of Worsening Pre-Election Border Anarchy  FAKE
 8055 A Reader Refers Us To Englishman Pat Condell On Brexit, The Trump Election, And "America's Moment Of Truth"  FAKE
 8816                                                         Paris Migrant Campers Increase after Calais Is Shut  FAKE
 5776                              Radio Derb Transcript For October 21 Up: The Magic Bricks Of PS 199, Et Cetera  FAKE
 7525                         Putins Army is coming for World war 3 against Obama year 2016!!! New Video!!! Kopya  FAKE
 6254                                                                     Paris: Riot Police Flatten Invader Camp  FAKE
 8240                                                        Democrats Playing Class Card To Split the White Vote  FAKE
10414                                         More on Trump's Populism and How It Can Be Controlled By Government  FAKE
 6773                                                                            WORLD WAR 3 – HILLARY V.S. TRUMP  FAKE

In [42]:
df.duplicated().sum()

np.int64(228)

In [43]:
# Inspect whether the repeated articles have consistent labels.
label_conflicts = (
    df_clean.groupby('text')['label']
    .nunique()
)

print(
    "Duplicate texts with conflicting labels:",
    (label_conflicts > 1).sum()
)

Duplicate texts with conflicting labels: 0

In [44]:
df_clean = df_clean.drop_duplicates(subset='text', keep='first').copy()

print("Rows remaining:", len(df_clean))
print("\nLabel distribution:")
print(df_clean['label'].value_counts())

Rows remaining: 6039

Label distribution:
label
FAKE    3060
REAL    2979
Name: count, dtype: int64

### EDA (EXPLORATORY DATA ANALYSIS)

In [45]:
# Examine the final dataset
print("Dataset shape:", df_clean.shape)
print("\nColumns:")
print(df_clean.columns.tolist())

print("\nData types:")
print(df_clean.dtypes)

print("\nMissing values:")
print(df_clean.isna().sum())

print("\nLabel distribution:")
print(df_clean['label'].value_counts())

Dataset shape: (6039, 4)

Columns:
['id', 'title', 'text', 'label']

Data types:
id       object
title    object
text     object
label    object
dtype: object

Missing values:
id       0
title    0
text     0
label    0
dtype: int64

Label distribution:
label
FAKE    3060
REAL    2979
Name: count, dtype: int64

In [46]:
# Check the text length

df_clean['text_length'] = df_clean['text'].str.len()

print(df_clean['text_length'].describe())

count     6039.000000
mean      4706.938566
std       4083.023784
min          1.000000
25%       1943.500000
50%       3812.000000
75%       6276.500000
max      32518.000000
Name: text_length, dtype: float64

In [47]:
# Compare text length by label to see whether FAKE and REAL articles have noticeably different text-length distributions.
print(
    df_clean.groupby('label')['text_length']
    .describe()
)

        count         mean          std   min     25%     50%     75%      max
label
FAKE   3060.0  3978.528758  4215.528607   1.0  1313.5  2610.0  5076.5  32518.0
REAL   2979.0  5455.154079  3800.259152  33.0  3045.0  4829.0  6946.5  32509.0

### Text Processing

This involves preparing the text so that it is suitable for the model.

In [48]:
# create one column containing both the headline and article body (text & title).

df_clean['model_text'] = (
    df_clean['title'].fillna('') + ' ' +
    df_clean['text'].fillna('')
)

df_clean.head(3)

,id,title,text,label,text_length,model_text
0,8476,You Can Smell Hillary's Fear,"Daniel Greenfield, a Shillman Journalism Fello...",FAKE,7518,You Can Smell Hillary's Fear Daniel Greenfield...
1,10294,Watch The Exact Moment Paul Ryan Committed Pol...,Google Pinterest Digg Linkedin Reddit Stumbleu...,FAKE,2646,Watch The Exact Moment Paul Ryan Committed Pol...
2,3608,Kerry to go to Paris in gesture of sympathy,U.S. Secretary of State John F. Kerry said Mon...,REAL,2543,Kerry to go to Paris in gesture of sympathy U....

In [49]:
# Process the text

import re

def preprocess_text(text):
    text = text.lower()
    
    # Remove URLs
    text = re.sub(r'http\S+|www\S+', '', text)
    
    # Remove HTML tags
    text = re.sub(r'<.*?>', '', text)
    
    # Remove extra whitespace
    text = re.sub(r'\s+', ' ', text)
    
    return text.strip()

In [50]:
# Apply the processed text to the model text column

df_clean['processed_text'] = df_clean['model_text'].apply(preprocess_text)

In [51]:
# view the dataframe 
df_clean.head(3)

,id,title,text,label,text_length,model_text,processed_text
0,8476,You Can Smell Hillary's Fear,"Daniel Greenfield, a Shillman Journalism Fello...",FAKE,7518,You Can Smell Hillary's Fear Daniel Greenfield...,you can smell hillary's fear daniel greenfield...
1,10294,Watch The Exact Moment Paul Ryan Committed Pol...,Google Pinterest Digg Linkedin Reddit Stumbleu...,FAKE,2646,Watch The Exact Moment Paul Ryan Committed Pol...,watch the exact moment paul ryan committed pol...
2,3608,Kerry to go to Paris in gesture of sympathy,U.S. Secretary of State John F. Kerry said Mon...,REAL,2543,Kerry to go to Paris in gesture of sympathy U....,kerry to go to paris in gesture of sympathy u....

In [52]:
# compare the processed_text and combined model_text
print("Before:")
print(df_clean['model_text'].iloc[0])

print("\nAfter:")
print(df_clean['processed_text'].iloc[0])

Before:
You Can Smell Hillary's Fear Daniel Greenfield, a Shillman Journalism Fellow at the Freedom Center, is a New York writer focusing on radical Islam.
In the final stretch of the election, Hillary Rodham Clinton has gone to war with the FBI.
The word "unprecedented" has been thrown around so often this election that it ought to be retired. But it's still unprecedented for the nominee of a major political party to go war with the FBI.
But that's exactly what Hillary and her people have done. Coma patients just waking up now and watching an hour of CNN from their hospital beds would assume that FBI Director James Comey is Hillary's opponent in this election.
The FBI is under attack by everyone from Obama to CNN. Hillary's people have circulated a letter attacking Comey. There are currently more media hit pieces lambasting him than targeting Trump. It wouldn't be too surprising if the Clintons or their allies were to start running attack ads against the FBI.
The FBI's leadership is being warned that the entire left-wing establishment will form a lynch mob if they continue going after Hillary. And the FBI's credibility is being attacked by the media and the Democrats to preemptively head off the results of the investigation of the Clinton Foundation and Hillary Clinton.
The covert struggle between FBI agents and Obama's DOJ people has gone explosively public.
The New York Times has compared Comey to J. Edgar Hoover. Its bizarre headline, "James Comey Role Recalls Hoover's FBI, Fairly or Not" practically admits up front that it's spouting nonsense. The Boston Globe has published a column calling for Comey's resignation. Not to be outdone, Time has an editorial claiming that the scandal is really an attack on all women.
James Carville appeared on MSNBC to remind everyone that he was still alive and insane. He accused Comey of coordinating with House Republicans and the KGB. And you thought the "vast right wing conspiracy" was a stretch.
Countless media stories charge Comey with violating procedure. Do you know what's a procedural violation? Emailing classified information stored on your bathroom server.
Senator Harry Reid has sent Comey a letter accusing him of violating the Hatch Act. The Hatch Act is a nice idea that has as much relevance in the age of Obama as the Tenth Amendment. But the cable news spectrum quickly filled with media hacks glancing at the Wikipedia article on the Hatch Act under the table while accusing the FBI director of one of the most awkward conspiracies against Hillary ever.
If James Comey is really out to hurt Hillary, he picked one hell of a strange way to do it.
Not too long ago Democrats were breathing a sigh of relief when he gave Hillary Clinton a pass in a prominent public statement. If he really were out to elect Trump by keeping the email scandal going, why did he trash the investigation? Was he on the payroll of House Republicans and the KGB back then and playing it coy or was it a sudden development where Vladimir Putin and Paul Ryan talked him into taking a look at Anthony Weiner's computer?
Either Comey is the most cunning FBI director that ever lived or he's just awkwardly trying to navigate a political mess that has trapped him between a DOJ leadership whose political futures are tied to Hillary's victory and his own bureau whose apolitical agents just want to be allowed to do their jobs.
The only truly mysterious thing is why Hillary and her associates decided to go to war with a respected Federal agency. Most Americans like the FBI while Hillary Clinton enjoys a 60% unfavorable rating.
And it's an interesting question.
Hillary's old strategy was to lie and deny that the FBI even had a criminal investigation underway. Instead her associates insisted that it was a security review. The FBI corrected her and she shrugged it off. But the old breezy denial approach has given way to a savage assault on the FBI.
Pretending that nothing was wrong was a bad strategy, but it was a better one that picking a fight with the FBI while lunatic Clinton associates try to claim that the FBI is really the KGB.
There are two possible explanations.
Hillary Clinton might be arrogant enough to lash out at the FBI now that she believes that victory is near. The same kind of hubris that led her to plan her victory fireworks display could lead her to declare a war on the FBI for irritating her during the final miles of her campaign.
But the other explanation is that her people panicked.
Going to war with the FBI is not the behavior of a smart and focused presidential campaign. It's an act of desperation. When a presidential candidate decides that her only option is to try and destroy the credibility of the FBI, that's not hubris, it's fear of what the FBI might be about to reveal about her.
During the original FBI investigation, Hillary Clinton was confident that she could ride it out. And she had good reason for believing that. But that Hillary Clinton is gone. In her place is a paranoid wreck. Within a short space of time the "positive" Clinton campaign promising to unite the country has been replaced by a desperate and flailing operation that has focused all its energy on fighting the FBI.
There's only one reason for such bizarre behavior.
The Clinton campaign has decided that an FBI investigation of the latest batch of emails poses a threat to its survival. And so it's gone all in on fighting the FBI. It's an unprecedented step born of fear. It's hard to know whether that fear is justified. But the existence of that fear already tells us a whole lot.
Clinton loyalists rigged the old investigation. They knew the outcome ahead of time as well as they knew the debate questions. Now suddenly they are no longer in control. And they are afraid.
You can smell the fear.
The FBI has wiretaps from the investigation of the Clinton Foundation. It's finding new emails all the time. And Clintonworld panicked. The spinmeisters of Clintonworld have claimed that the email scandal is just so much smoke without fire. All that's here is the appearance of impropriety without any of the substance. But this isn't how you react to smoke. It's how you respond to a fire.
The misguided assault on the FBI tells us that Hillary Clinton and her allies are afraid of a revelation bigger than the fundamental illegality of her email setup. The email setup was a preemptive cover up. The Clinton campaign has panicked badly out of the belief, right or wrong, that whatever crime the illegal setup was meant to cover up is at risk of being exposed.
The Clintons have weathered countless scandals over the years. Whatever they are protecting this time around is bigger than the usual corruption, bribery, sexual assaults and abuses of power that have followed them around throughout the years. This is bigger and more damaging than any of the allegations that have already come out. And they don't want FBI investigators anywhere near it.
The campaign against Comey is pure intimidation. It's also a warning. Any senior FBI people who value their careers are being warned to stay away. The Democrats are closing ranks around their nominee against the FBI. It's an ugly and unprecedented scene. It may also be their last stand.
Hillary Clinton has awkwardly wound her way through numerous scandals in just this election cycle. But she's never shown fear or desperation before. Now that has changed. Whatever she is afraid of, it lies buried in her emails with Huma Abedin. And it can bring her down like nothing else has.

After:
you can smell hillary's fear daniel greenfield, a shillman journalism fellow at the freedom center, is a new york writer focusing on radical islam. in the final stretch of the election, hillary rodham clinton has gone to war with the fbi. the word "unprecedented" has been thrown around so often this election that it ought to be retired. but it's still unprecedented for the nominee of a major political party to go war with the fbi. but that's exactly what hillary and her people have done. coma patients just waking up now and watching an hour of cnn from their hospital beds would assume that fbi director james comey is hillary's opponent in this election. the fbi is under attack by everyone from obama to cnn. hillary's people have circulated a letter attacking comey. there are currently more media hit pieces lambasting him than targeting trump. it wouldn't be too surprising if the clintons or their allies were to start running attack ads against the fbi. the fbi's leadership is being warned that the entire left-wing establishment will form a lynch mob if they continue going after hillary. and the fbi's credibility is being attacked by the media and the democrats to preemptively head off the results of the investigation of the clinton foundation and hillary clinton. the covert struggle between fbi agents and obama's doj people has gone explosively public. the new york times has compared comey to j. edgar hoover. its bizarre headline, "james comey role recalls hoover's fbi, fairly or not" practically admits up front that it's spouting nonsense. the boston globe has published a column calling for comey's resignation. not to be outdone, time has an editorial claiming that the scandal is really an attack on all women. james carville appeared on msnbc to remind everyone that he was still alive and insane. he accused comey of coordinating with house republicans and the kgb. and you thought the "vast right wing conspiracy" was a stretch. countless media stories charge comey with violating procedure. do you know what's a procedural violation? emailing classified information stored on your bathroom server. senator harry reid has sent comey a letter accusing him of violating the hatch act. the hatch act is a nice idea that has as much relevance in the age of obama as the tenth amendment. but the cable news spectrum quickly filled with media hacks glancing at the wikipedia article on the hatch act under the table while accusing the fbi director of one of the most awkward conspiracies against hillary ever. if james comey is really out to hurt hillary, he picked one hell of a strange way to do it. not too long ago democrats were breathing a sigh of relief when he gave hillary clinton a pass in a prominent public statement. if he really were out to elect trump by keeping the email scandal going, why did he trash the investigation? was he on the payroll of house republicans and the kgb back then and playing it coy or was it a sudden development where vladimir putin and paul ryan talked him into taking a look at anthony weiner's computer? either comey is the most cunning fbi director that ever lived or he's just awkwardly trying to navigate a political mess that has trapped him between a doj leadership whose political futures are tied to hillary's victory and his own bureau whose apolitical agents just want to be allowed to do their jobs. the only truly mysterious thing is why hillary and her associates decided to go to war with a respected federal agency. most americans like the fbi while hillary clinton enjoys a 60% unfavorable rating. and it's an interesting question. hillary's old strategy was to lie and deny that the fbi even had a criminal investigation underway. instead her associates insisted that it was a security review. the fbi corrected her and she shrugged it off. but the old breezy denial approach has given way to a savage assault on the fbi. pretending that nothing was wrong was a bad strategy, but it was a better one that picking a fight with the fbi while lunatic clinton associates try to claim that the fbi is really the kgb. there are two possible explanations. hillary clinton might be arrogant enough to lash out at the fbi now that she believes that victory is near. the same kind of hubris that led her to plan her victory fireworks display could lead her to declare a war on the fbi for irritating her during the final miles of her campaign. but the other explanation is that her people panicked. going to war with the fbi is not the behavior of a smart and focused presidential campaign. it's an act of desperation. when a presidential candidate decides that her only option is to try and destroy the credibility of the fbi, that's not hubris, it's fear of what the fbi might be about to reveal about her. during the original fbi investigation, hillary clinton was confident that she could ride it out. and she had good reason for believing that. but that hillary clinton is gone. in her place is a paranoid wreck. within a short space of time the "positive" clinton campaign promising to unite the country has been replaced by a desperate and flailing operation that has focused all its energy on fighting the fbi. there's only one reason for such bizarre behavior. the clinton campaign has decided that an fbi investigation of the latest batch of emails poses a threat to its survival. and so it's gone all in on fighting the fbi. it's an unprecedented step born of fear. it's hard to know whether that fear is justified. but the existence of that fear already tells us a whole lot. clinton loyalists rigged the old investigation. they knew the outcome ahead of time as well as they knew the debate questions. now suddenly they are no longer in control. and they are afraid. you can smell the fear. the fbi has wiretaps from the investigation of the clinton foundation. it's finding new emails all the time. and clintonworld panicked. the spinmeisters of clintonworld have claimed that the email scandal is just so much smoke without fire. all that's here is the appearance of impropriety without any of the substance. but this isn't how you react to smoke. it's how you respond to a fire. the misguided assault on the fbi tells us that hillary clinton and her allies are afraid of a revelation bigger than the fundamental illegality of her email setup. the email setup was a preemptive cover up. the clinton campaign has panicked badly out of the belief, right or wrong, that whatever crime the illegal setup was meant to cover up is at risk of being exposed. the clintons have weathered countless scandals over the years. whatever they are protecting this time around is bigger than the usual corruption, bribery, sexual assaults and abuses of power that have followed them around throughout the years. this is bigger and more damaging than any of the allegations that have already come out. and they don't want fbi investigators anywhere near it. the campaign against comey is pure intimidation. it's also a warning. any senior fbi people who value their careers are being warned to stay away. the democrats are closing ranks around their nominee against the fbi. it's an ugly and unprecedented scene. it may also be their last stand. hillary clinton has awkwardly wound her way through numerous scandals in just this election cycle. but she's never shown fear or desperation before. now that has changed. whatever she is afraid of, it lies buried in her emails with huma abedin. and it can bring her down like nothing else has.

### Model Building

#### Train / Test split

In [53]:
# Train / Test split

from sklearn.model_selection import train_test_split

X = df_clean['processed_text']
y = df_clean['label']

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training samples:", len(X_train))
print("Testing samples:", len(X_test))

print("\nTraining labels:")
print(y_train.value_counts())

print("\nTesting labels:")
print(y_test.value_counts())

Training samples: 4831
Testing samples: 1208

Training labels:
label
FAKE    2448
REAL    2383
Name: count, dtype: int64

Testing labels:
label
FAKE    612
REAL    596
Name: count, dtype: int64

### Feature extraction/vectorization

The model cannot directly understand:
"the government announced a new policy..."

We need to convert the text into numerical features and we'll use TF-IDF (Term Frequency–Inverse Document Frequency) to achieve.

In [54]:
# Import TF-IDF

from sklearn.feature_extraction.text import TfidfVectorizer

In [55]:
# Create the Vectorizer

tfidf = TfidfVectorizer(
    max_features=50000, # use at most 50,000 features
    ngram_range=(1, 2), # Use individual words and two-words combinations
    min_df=2, # ignore words appearing in only one document
    max_df=0.95 # ignore words appearing in more than 95% of documents
)

In [56]:
# Fit the vectorizer on the training data(Text)

X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

In [57]:
# Print the result

print("Training TF-IDF shape:", X_train_tfidf.shape)
print("Testing TF-IDF shape:", X_test_tfidf.shape)

Training TF-IDF shape: (4831, 50000)
Testing TF-IDF shape: (1208, 50000)

#### Model Training -- Logistic Regression

This model will ask: Based on these words/features, what is the probability that this article belongs to each class?

In [58]:
# Let's train a baseline model using LogisticRegression

from sklearn.linear_model import LogisticRegression

model_log = LogisticRegression(
    max_iter=1000,
    random_state=42
)

model_log.fit(X_train_tfidf, y_train)

LogisticRegression(max_iter=1000, random_state=42)

In [59]:
# make prediction with the trained Model

y_pred = model_log.predict(X_test_tfidf)

print(y_pred[:20])

['FAKE' 'FAKE' 'FAKE' 'FAKE' 'REAL' 'FAKE' 'FAKE' 'FAKE' 'REAL' 'REAL'
 'FAKE' 'FAKE' 'REAL' 'FAKE' 'FAKE' 'FAKE' 'REAL' 'REAL' 'FAKE' 'FAKE']

#### Model Evaluation

In [60]:
# Import the evaluation mertic libraries

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix
)

In [61]:
# Evaluate the model using the imported libraries
# pos_label tells machine learning to focu on 'FAKE' when calculating precision, recall, and F1.
# So we're simply defining it as the class of interest for this particular evaluation.

log_accuracy = accuracy_score(y_test, y_pred)
log_precision = precision_score(y_test, y_pred, pos_label='FAKE')
log_recall = recall_score(y_test, y_pred, pos_label='FAKE')
log_f1 = f1_score(y_test, y_pred, pos_label='FAKE')

print("Accuracy :", round(log_accuracy, 2))
print("Precision:", round(log_precision, 2))
print("Recall   :", round(log_recall, 2))
print("F1 Score :", round(log_f1, 2))

Accuracy : 0.91
Precision: 0.89
Recall   : 0.94
F1 Score : 0.91

In [62]:
# Get the Classification report

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Classification Report:
              precision    recall  f1-score   support

        FAKE       0.89      0.94      0.91       612
        REAL       0.93      0.88      0.91       596

    accuracy                           0.91      1208
   macro avg       0.91      0.91      0.91      1208
weighted avg       0.91      0.91      0.91      1208

In [63]:
# Evaluate the confusion matrix

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Confusion Matrix:
[[573  39]
 [ 70 526]]

#### The Logistics Regression Model Performance:
The Logistic Regression model achieved 91% accuracy on the test set, with an F1-score of 0.91 for both FAKE and REAL classes. 
The model achieved 94% recall for FAKE news, correctly identifying 573 of the 612 fake articles in the test set.

### 2nd Model Training -- LINEAR SVM

we're specifically using a Linear SVM because our input is TF-IDF text data.

The basic idea is:
Linear SVM will try to find the best boundary that separates FAKE articles from REAL articles.

In [64]:
# import LinearSVM
from sklearn.svm import LinearSVC

In [65]:
#Instantiate and train the model

svm_model = LinearSVC(
    random_state=42,
    max_iter = 2000
)

svm_model.fit(X_train_tfidf, y_train)

LinearSVC(max_iter=2000, random_state=42)

In [66]:
# Make predictions

y_pred_svm= svm_model.predict(X_test_tfidf)
print(y_pred_svm[:20])

['FAKE' 'FAKE' 'FAKE' 'FAKE' 'REAL' 'FAKE' 'FAKE' 'FAKE' 'REAL' 'REAL'
 'FAKE' 'FAKE' 'REAL' 'FAKE' 'FAKE' 'FAKE' 'REAL' 'REAL' 'FAKE' 'FAKE']

In [67]:
# Evaluate the models performance

svm_accuracy= accuracy_score(y_test, y_pred_svm)

svm_precision = precision_score(
    y_test, y_pred_svm, pos_label='FAKE'
)

svm_recall = recall_score(
    y_test, y_pred_svm, pos_label='FAKE'
)

svm_f1 = f1_score(
    y_test, y_pred_svm, pos_label='FAKE'
)

print("Linear SVM Evaluation")
print("---------------------")
print(f"Accuracy : {svm_accuracy:.2f}")
print(f"Precision: {svm_precision:.2f}")
print(f"Recall   : {svm_recall:.2f}")
print(f"F1 Score : {svm_f1:.2f}")

print("\nClassification Report:")
print(classification_report(y_test, y_pred_svm))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_svm))

Linear SVM Evaluation
---------------------
Accuracy : 0.93
Precision: 0.92
Recall   : 0.95
F1 Score : 0.94

Classification Report:
              precision    recall  f1-score   support

        FAKE       0.92      0.95      0.94       612
        REAL       0.95      0.92      0.93       596

    accuracy                           0.93      1208
   macro avg       0.93      0.93      0.93      1208
weighted avg       0.93      0.93      0.93      1208


Confusion Matrix:
[[582  30]
 [ 50 546]]

#### Linear SVM Model performance:

The Linear Support Vector Machine (SVM) model achieved **93% accuracy** on the test dataset. 

It recorded a precision of **92%**, recall of **95%**, and F1-score of **0.94** for the FAKE class. For the REAL class, it achieved 95% precision, 92% recall, and an F1-score of 0.93. The overall macro F1-score was 0.93, indicating balanced performance across both classes. 

These results show that the model performed well on the test dataset, although further error analysis is needed to understand its limitations and reliability on unseen real-world news.

### Error Analysis

The aim for this is to investigate the articles the linear svm classified incorrectly and try to undestand why.

In [68]:
# create a dataframe of the predictions
error_df = pd.DataFrame({
    'article': X_test,
    'actual_label': y_test,
    'predicted_label': y_pred_svm
})

# filter the table to keep only incorrect predictions
error_df = error_df[
    error_df['actual_label'] != error_df['predicted_label']
].copy()

# show samples of the mistakes for investigation
print("Total misclassified articles:", len(error_df))
print(error_df.head())

Total misclassified articles: 80
                                                article actual_label  \
3437  hillary clinton enjoys solid lead in early vot...         FAKE
1523  fear of trump sparking a surge in citizenship,...         REAL
7317  memo to trump: 'action this day!' => "in victo...         FAKE
6859  kate steinle's death and sanctuary cities: wha...         REAL
2153  clinton emails on trade deal held until after ...         REAL

     predicted_label
3437            REAL
1523            FAKE
7317            REAL
6859            FAKE
2153            FAKE

In [69]:
# Check the mistakes


print(
    pd.crosstab(
        error_df['actual_label'],
        error_df['predicted_label'],
        rownames=['Actual'],
        colnames=['Predicted']
    )
)

Predicted  FAKE  REAL
Actual
FAKE          0    30
REAL         50     0

These are how many REAL articles were classified as FAKE and how many FAKE articles were classified as REAL.

In [70]:
# Inspect some of the misclassified Artices

for _, row in error_df.head(5).iterrows():
    print("Actual label:   ", row['actual_label'])
    print("Predicted label:", row['predicted_label'])
    print("Article:")
    print(row['article'][:1000])
    print("-" * 80)

Actual label:    FAKE
Predicted label: REAL
Article:
hillary clinton enjoys solid lead in early voting: reuters/ipsos poll by reuters 5:51 pm democratic nominee hillary clinton leads republican donald trump by 15 percentage points among early voters surveyed in the past two weeks, according to the reuters/ipsos states of the nation project. by maurice tamman new york (reuters) – with 11 days to go before the u.s. presidential election, democratic nominee hillary clinton leads republican donald trump by 15 percentage points among early voters surveyed in the past two weeks, according to the reuters/ipsos states of the nation project. though data is not available for all early voting states, clinton enjoys an edge in swing states such as ohio and arizona and in republican party strongholds such as georgia and texas. an estimated 19 million americans have voted so far in the election, according to the university of florida's united states election project, accounting for as much as 20 percent of the electorate. overall, clinton remained on
--------------------------------------------------------------------------------
Actual label:    REAL
Predicted label: FAKE
Article:
fear of trump sparking a surge in citizenship, voter applications - the campaign of the presumptive republican nominee, donald trump, is sparking a surge in the number of citizenship applications and voter registrations among hispanics fearful of his immigration policies. since january, california alone has seen a boost of 218 percent in democratic registration and among hispanics, registration is up 123 percent. ()
--------------------------------------------------------------------------------
Actual label:    FAKE
Predicted label: REAL
Article:
memo to trump: 'action this day!' => "in victory, magnanimity!" said winston churchill. donald trump should be magnanimous and gracious toward those whom he defeated this week, but his first duty is to keep faith with those who put their faith in him. the protests, riots and violence that have attended his triumph in city after city should only serve to steel his resolve. as for promptings that he "reach out" and "reassure" those upset by his victory, and trim or temper his agenda to pacify them, trump should reject the poisoned chalice. this is the same old con. trump should take as models the democrats fdr and lbj. franklin roosevelt, who had savaged herbert hoover as a big spender, launched his own new deal in his first 100 days. history now hails his initiative and resolve. lyndon johnson exploited his landslide over barry goldwater in 1964 to erect his great society in 1965: the voting rights act, medicare and medicaid. he compromised on nothing, and got it all. even those who tur
--------------------------------------------------------------------------------
Actual label:    REAL
Predicted label: FAKE
Article:
kate steinle's death and sanctuary cities: what good are our laws without enforcement? according to the wall street journal, the last serious attempt to count the number of federal criminal laws appears to have been made in 1982 by a retired justice department official named ronald gainer. he failed, but the estimate then was "…50 titles and 23,000 pages of federal law." many more laws have been added since then. one thing is certain: if you violate federal law you are likely to be punished with a fine, imprisonment or both. these laws are supposed to apply to everyone, unless, it seems, you are an illegal alien living in san francisco, or any of the other sanctuary cities around the country. by now, anyone not preoccupied with stories about shark attacks, the confederate flag or singer ariana grande "maliciously licking" donuts she did not buy, has heard about 32-year-old kathryn steinle gunned down by an illegal alien while walking on a san francisco pier with her father. her accused
--------------------------------------------------------------------------------
Actual label:    REAL
Predicted label: FAKE
Article:
clinton emails on trade deal held until after election - video clinton emails on trade deal held until after election
--------------------------------------------------------------------------------

Three useful observations i found out:
- Text completeness matters. Short headlines or incomplete articles provide less information than full articles.
- Writing style can be misleading. News reporting, commentary, and emotionally worded text may overlap across the two labels.
- The dataset labels need context. An incorrect prediction relative to the dataset does not automatically mean the article's label is objectively correct or incorrect.

Next: Inspect the model's remaining errors to see whether these patterns are widespread or whether the five examples are unusual.

In [71]:
# Count errors by actual and predicted class
print(
    error_df.groupby(
        ['actual_label', 'predicted_label']
    ).size()
)

# Inspect the shortest misclassified articles
error_df['article_length'] = error_df['article'].str.len()

print(
    error_df[
        ['actual_label', 'predicted_label', 'article_length', 'article']
    ]
    .sort_values('article_length')
    .head(10)
    .to_string(index=False)
)

actual_label  predicted_label
FAKE          REAL               30
REAL          FAKE               50
dtype: int64
actual_label predicted_label  article_length                                                                                                                                                                                                                                                                                                                                                                                                                                                                           article
        REAL            FAKE              82                                                                                                                                                                                                                                                                                                                                                                                                7 times obama failed to support israel should the u.s. continue to support israel?
        REAL            FAKE             110                                                                                                                                                                                                                                                                                                                                                                    exclusive: hillary may delay campaign "trump's plan to repair our infrastructure is a scam," sanders declares.
        REAL            FAKE             112                                                                                                                                                                                                                                                                                                                                                                  how congress finally killed no child left behind parker covered the trump campaign and transition for the times.
        REAL            FAKE             117                                                                                                                                                                                                                                                                                                                                                             clinton emails on trade deal held until after election - video clinton emails on trade deal held until after election
        REAL            FAKE             136                                                                                                                                                                                                                                                                                                                                          poll: rubio leads the gop pack in matchup against clinton london is kidding itself if it thinks this will be a negotiation among equals.
        REAL            FAKE             172                                                                                                                                                                                                                                                                                                      in this political ad the wife of a candidate defending his seat on the travis county commissioners court implores voters to reelect him so that he'll get out of the house:"
        REAL            FAKE             180                                                                                                                                                                                                                                                                                              shutdown clash to return in force by december notable names include ray washburne (commerce), a dallas-based investor, is reported to be under consideration to lead the department.
        REAL            FAKE             185                                                                                                                                                                                                                                                                                         gop insiders: carly crushed it on this day in 1973, j. fred buzhardt, a lawyer defending president richard nixon in the watergate case, revealed that a key white house tape had an 18...
        REAL            FAKE             419                                               fear of trump sparking a surge in citizenship, voter applications - the campaign of the presumptive republican nominee, donald trump, is sparking a surge in the number of citizenship applications and voter registrations among hispanics fearful of his immigration policies. since january, california alone has seen a boost of 218 percent in democratic registration and among hispanics, registration is up 123 percent. ()
        REAL            FAKE             465 where donald trump and hillary clinton stand on economic issues in the end, elections usually come back to the economy—to jobs, wages, taxes, imports and exports, the price of goods and the cost of an education. differences over all these issues—from tax rates and immigration to globalization and the minimum wage—are particularly sharp this year between donald trump and hillary clinton. here's a look at where the two candidates stand on the top economic issues.

With these output: I have analyzed the Articles text with LLM, and there are two recurring issues:

- Short or incomplete text: Some inputs combine a headline with unrelated text, end abruptly, or contain very little context.
- Mixed content: Some articles appear to contain snippets from multiple stories. For example, a headline may be followed by text about a different person or topic.


These patterns suggest possible data-quality problems, it is not necessarily flaws in the SVM algorithm. The model classifies the text it receives; and it cannot reliably reconstruct missing context. 

- So far this error Analysis has provided a good pattern recognition on why some misclassification occurs.

## Save Model

I will save the Linear SVM and TF-IDF vectorizer as a single scikit-learn pipeline. It will make this Fake News Detection project easier to reuse and deploy.

This model is selected because it outperformed the logistic Regression.

In [73]:
# import pipeline and preprocessing function

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import FunctionTransformer

In [75]:
# Define a preprocessing function to process thye text into a more consistent and readable format

import re

def preprocess_texts(texts):
    cleaned_texts = []

    for text in texts:
        text = str(text).lower()
        text = re.sub(r'http\S+|www\S+', '', text)
        text = re.sub(r'<.*?>', '', text)
        text = re.sub(r'\s+', ' ', text).strip()
        cleaned_texts.append(text)

    return cleaned_texts

In [76]:
fake_news_pipeline = Pipeline([
    # Text preprocessing
    ('preprocessing', FunctionTransformer(
        preprocess_texts,
        validate=False
    )),
    # the tfidf converts raw text into numerical features.
    ('tfidf', TfidfVectorizer(  
        max_features=50000,
        ngram_range=(1, 2),
        min_df=2,
        max_df=0.95
    )),
    # the svm classifies the features as FAKE or REAL.
    ('svm', LinearSVC(
        random_state=42,
        max_iter=2000
    ))
])

In [77]:
# prepare the raw data and split with the already concatenated text and title column (model_text)
X = df_clean['model_text']
y = df_clean['label']

X_train_raw, X_test_raw, y_train_raw, y_test_raw = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training samples:", len(X_train_raw))
print("Testing samples:", len(X_test_raw))

Training samples: 4831
Testing samples: 1208

In [78]:
# pipeline training with the training preprocessed data 
# This will fit the TF-IDF vectorizer on the training text and then trains Linear SVM on the resulting features.

fake_news_pipeline.fit(X_train_raw, y_train_raw)
print("Pipeline training completed")

Pipeline training completed

In [79]:
# Evaluate the pipeline to ensure it performs well as expected on the test data

y_pred_pipeline = fake_news_pipeline.predict(X_test_raw)

print("Pipeline Accuracy:", round(
    accuracy_score(y_test_raw, y_pred_pipeline), 4
))

print(classification_report(y_test_raw, y_pred_pipeline))

Pipeline Accuracy: 0.9338
              precision    recall  f1-score   support

        FAKE       0.92      0.95      0.94       612
        REAL       0.95      0.92      0.93       596

    accuracy                           0.93      1208
   macro avg       0.93      0.93      0.93      1208
weighted avg       0.93      0.93      0.93      1208

In [80]:
# Save the model using joblib
import joblib

joblib.dump(fake_news_pipeline, 'fake_news_pipeline.joblib')

# confirm the saving is successfull
print("Pipeline saved successfully")

Pipeline saved successfully

In [81]:
# Load and verify the loaded pipeline

loaded_pipeline = joblib.load(
    'fake_news_pipeline.joblib'
)

print("Pipeline loaded successfully.")

Pipeline loaded successfully.

In [84]:
# compare predictions from the original fitted pipeline and the loaded one

sample_article = X_test_raw.iloc[0]

original_predictions = fake_news_pipeline.predict(sample_article)
loaded_predictions = loaded_pipeline.predict([sample_article])

# Displays the first predictions and assertain if the two predictions are matched
print("Original predictions:", original_predictions)
print("Loaded predictions:  ", loaded_predictions)

assert (original_predictions == loaded_predictions).all()

print("Verification successful: predictions match.")

Original predictions: ['FAKE' 'FAKE' 'FAKE' ... 'FAKE' 'FAKE' 'FAKE']
Loaded predictions:   ['FAKE']
Verification successful: predictions match.

 #### Test a new article

Test the model with a new input that wasn't taken from the test set

In [85]:
new_article = """
Example headline: Local authorities announce a new public transport plan.
The transport department released details of the proposal on Monday.
"""

prediction = loaded_pipeline.predict([new_article])

print("Predicted label:", prediction[0])

Predicted label: REAL